### ISSUE TITLE
Project specification is not met - total price of order

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#100]
The system will also be able to provide an overview of all orders by customer, total order price, etc.

**Comment by Jeld4** [comment]
Admin can search all orders by user this way: All users - choose the concrete user - it opens user info, where are also all his orders.
Total order price calculation fixed.
Commit: https://github.com/Jeld4/pa165_project/commit/414053680b128983456c513d59e0c2d3a813a881
