### ISSUE TITLE
User.equals - very hard to read

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#26]
The equals method is very hard to read. Have you tried to use the ide's functionality for the generating equals method? 

btw, think about this. 
new User ("Ahoj", "nAME" ,"pASSWORD")
new User ("aHOJ", "Name" ,"Password")
Should be those two users the same or not why?

**Comment by vpapiez** [comment]
this one is hard to read as well OrderCreateDTO.equals. java.utils.Objects has nice set of functions. Try them.

**Comment by xmaly** [comment]
User.equals is now generated by id.
https://github.com/Jeld4/pa165_project/commit/cacbc61a475cff283b6081b0e658203d80dfba3a
