### ISSUE TITLE
No constraints

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#28]
There are no constrains for entities. I can create an order with a null date of order. empty list of tires. I would challenge that. Why there are no constraints at all in the project?

**Comment by Jeld4** [comment]
Order constraints solved.

**Comment by MichalKlima** [comment]
fixed for user

**Comment by xmaly** [comment]
Tire constraints solved https://github.com/Jeld4/pa165_project/commit/6dbe8a1bf9dede317cc7a89112e4b4566f391c57
