### ISSUE TITLE
OrderDaoImplTest 

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#30]
Missing negative tests. what happen when you call
orderDao.delete(null). Is your code ready for this?

**Comment by Jeld4** [comment]
Updated OrderDaoImplTest to test also negative cases.
https://github.com/Jeld4/pa165_project/commit/1c65b93b51605e0a796cd62b5c17264314da02e5

**Comment by Jeld4** [comment]
Removed else for better reading of the code
https://github.com/Jeld4/pa165_project/commit/b68971e4df5debe302a8e9a070d038d6614398c2
