### ISSUE TITLE
Entities should use @Table

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#35]
Entities should annotation Table to specify the table name. I recommend to study why.

**Comment by Jeld4** [comment]
Updated entities to use @table annotation. But why is it so important? I see no other use than to override the name of the table or to enforce unique constraints on columns in the table.
https://github.com/Jeld4/pa165_project/commit/b485a01a323abb20b0de2f56f8bccebcca2c81ce

**Comment by vpapiez** [comment]
What does the uncle google said? 

https://lmgtfy.com/?q=%40entity+vs+%40table
