### ISSUE TITLE
Entities should implement Serializable

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#36]
I recommend to learn why

**Comment by 456315** [comment]
Is there a reason why there is no implementation of Serializable in example project?

**Comment by vpapiez** [comment]
I would not argument this way. I would recommend to learn the interface and what it allows to your project/entities.

There are a lot of thing missing in the example project. Many of them are there which are missed in this project.

**Comment by 456315** [comment]
I understand, but it feel underwhelming being crititsized for something that is not in the assignment nor the example.

**Comment by vpapiez** [comment]
I am sorry if you feel criticised. Code review can be felt that way but it is not at all. You starts with programming and you will make mistakes. You will make them even after 10 years! a developer in my team with huge respect just forgot "this." in a setter method and it caused a lot of issues and took us time to find the bug. Everybody makes mistakes. Even i do. 

btw, why an entity should have Serializable? 

You are not here to learn only what is in the subject and preciously just in the subject. It is expect from you to learn more than that. The subject will just show you couple of ways. not all of them....
