### ISSUE TITLE
DTOs missing javadoc for public methods

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#42]
There are missing javadocs for the public methods.  Not just the method declaration, but the text is part of the contract. For example if there is a limitation it should be described in the javadoc text as well.

**Comment by Jeld4** [comment]
Added javadoc for public methods in DTOs.
https://github.com/Jeld4/pa165_project/commit/9653a6b7e288ac2bb1c5ef9f33c3c0b5b80f3a4e
