### ISSUE TITLE
NPE in ServiceCreateDTO.equals

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#45]
ServiceCreateDTO serviceEmpty = new ServiceCreateDTO();

ServiceCreateDTO serviceFullName = new ServiceCreateDTO();
serviceFullName.setName("serviceFullName");

ServiceCreateDTO serviceFullDescription = new ServiceCreateDTO();
serviceFullDescription = new ServiceCreateDTO();

service.equals(serviceFullName);
service.equals(serviceFullDescription);

**Comment by xmaly** [comment]
Fixed. ServiceCreateDTO.equals() now works correctly.
https://github.com/Jeld4/pa165_project/commit/0e15c63504e907d6858418b04dacf75c063140e0
