### ISSUE TITLE
extensive unit tests for the service layer

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#52]
There must be extensive unit tests for the service layer (particularly for your 2 business functions) and all the tests of service layer must use Mock DAO objects;

**Comment by Jeld4** [comment]
Done for Car and Order: https://github.com/Jeld4/pa165_project/commit/e86c44e0348f74694874a1b1eb10fc5616353320
https://github.com/Jeld4/pa165_project/commit/65b30d14eb571009438fe96092122921d547222e

**Comment by 456315** [comment]
User and Tire done
