### ISSUE TITLE
No logging

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#53]
There is no logging at at. I would recommend to introduce log4j/slf4j into the project.

**Comment by Jeld4** [comment]
logging for Order DONE: https://github.com/Jeld4/pa165_project/commit/a3fd1b3a13be39be380323c7bc674f3fee7016b9

**Comment by 456315** [comment]
cars and service DONE

**Comment by xmaly** [comment]
tire DONE https://github.com/Jeld4/pa165_project/commit/f1c3de5374ede8f33546dad69f70f409dffb37ce

**Comment by xmaly** [comment]
user DONE https://github.com/Jeld4/pa165_project/commit/8e752c5dd579873b47698c44045477f216578219
