### ISSUE TITLE
double Edit button in All Tires list

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#88]
![Screenshot 2020-06-01 at 09 36 50](https://user-images.githubusercontent.com/19915837/83386555-89a2a080-a3eb-11ea-9a07-fd45f655dfeb.png)

**Comment by xmaly** [comment]
https://github.com/Jeld4/pa165_project/pull/116/commits/1b5a3a3944892e0885f29199ba540d705acd0be6
