### ISSUE TITLE
Delete Tire button  does not work

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#89]
When I press the Delete button on a tire record, it does nothing. The button is clicked. No request is sent to backend from the browser network console

str:
navigate to the app /pa165
click to Tire offer
click to which every tire detail you want
click delete

Expected result:
tire is deleted
Actual result:
tire is not deleted, request is not send to backend

**Comment by xmaly** [comment]
https://github.com/Jeld4/pa165_project/pull/116/commits/1b5a3a3944892e0885f29199ba540d705acd0be6
