### ISSUE TITLE
Delete Service

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#90]
When I press the Delete button on a service record, it does nothing. The button is clicked. No request is sent to backend from the browser network console

str:
navigate to the app /pa165
click to service offer
click to which every service detail you want
click delete

Expected result:
service is deleted
Actual result:
service is not deleted, request is not send to backend

**Comment by xmaly** [comment]
https://github.com/Jeld4/pa165_project/pull/116/commits/1b5a3a3944892e0885f29199ba540d705acd0be6
