### ISSUE TITLE
Order Details

### ISSUE THREAD

**Issue by vpapiez** [Jeld4/pa165_project#92]
There is no detail for already created orders.

STR:
login as a user
navigate to User Info
Navigate to orders via a Detail button

AR:
no deatils are returned from backend - json is empty
no details are visible on the UI

ER:
I can see list of tires or services ordered together with the order status.

**Comment by Jeld4** [comment]
Order detail fixed..
Login as a user,
navigate to User Info,
select the order and click Detail button
----------------------------------
Page with order detail shows up.
1. Order id, date of order, State
2. Table of tires that belong to the order
3. Table of services that belong to the order
4. Total order price
----------------------------------
Commit: https://github.com/Jeld4/pa165_project/commit/2e62fc8b022f71781559a40806915ca0330689c3
